name: Spoofer
options:
  bundleIdPrefix: com.spoofer
targets:
  Spoofer:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - Spoofer
    info:
      path: Spoofer/Info.plist
      properties:
        UILaunchScreen: {}
